services:
  app:
    image: painel.git2.palmas.to.gov.br:5050/prestadores-servicos/consulta-publica:latest
    pull_policy: always
    restart: unless-stopped
    hostname: participe.palmas.to.gov.br
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    volumes:
      - bundle:/usr/local/bundle
      - node_modules:/var/www/consul/node_modules
      - storage:/var/www/consul/storage
    networks:
      - default
      - proxy
    environment:
      - DB_HOST=${DB_HOST}
      - PG_USER=${POSTGRES_USER}
      - PG_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.consulta-publica-http.rule=Host(`participe.palmas.to.gov.br`)"
      - "traefik.http.routers.consulta-publica-http.entrypoints=web"
      - "traefik.http.routers.consulta-publica-https.rule=Host(`participe.palmas.to.gov.br`)"
      - "traefik.http.routers.consulta-publica-https.entrypoints=websecure"
      - "traefik.http.routers.consulta-publica-https.tls=true"
      - "traefik.http.routers.consulta-publica-https.tls.certresolver=letsencrypt"
      - "traefik.http.services.consulta-publica.loadbalancer.server.port=3000"
networks:
  default:
    name: consulta-publica_default
  proxy:
    external: true
volumes:
  db_data: {}
  bundle: {}
  node_modules: {}
  storage: {}
