# .github/workflows/mirror-to-gitlab.yml
name: Mirror to GitLab
on: [push]
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@painel.git2.palmas.to.gov.br/prestadores-servicos/consulta-publica.git
          git push gitlab --mirror
